
server:
  port: 8000
  ssl:
    enabled: true
    key-store: ${CERTIFICATE_PATH:media-service/certificate/keystore.p12}
    key-store-password: 'changeit'
    key-store-type: 'PKCS12'
    key-alias: 'myapp'
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          routes:
            - id: media-service
              uri: ${MEDIA_SERVICE_URI:https://localhost:9000}
              predicates:
                - Path=/api/v1/images/**,/api/v1/files/**

            - id: identity-service
              uri: ${IDENTITY_SERVICE_URI:https://localhost:9010}
              predicates:
                - Path=/api/v1/security/**