
services:

  postgres:
    container_name: course-service-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5020:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course-service-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: